name: verify_version

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  verify-version:
    if: github.head_ref == 'release-please--branches--main--components--very_good_analysis'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dart-lang/setup-dart@v1

      - name: Verify version consistency
        run: dart run tool/verify_version/main.dart
